version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/gradle-sample"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
# dependabot document
# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
